# fly.toml app configuration file generated for autoflow on 2023-12-30T14:04:33Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "autoflow"
primary_region = "sjc"

[build]

[mounts]
  source = "autoflow_data"
  destination = "/home/node/.n8n"

[http_service]
  internal_port = 5678
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
